
name: Transform tokens send from figma
on:
  repository_dispatch:
    types: update-tokens
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: mkdir "tokens" directory
        run: 'mkdir -p tokens'

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'design-tokens.json'
          json: ${{ github.event.client_payload.tokens }}
          dir: 'tokens'

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Transform design tokens 
        run: 'npm i && npm run transform-tokens'
     
      - name: Persist changes in repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'